[package]
name = "dpml"
version = "0.1.0"
edition = "2024"
default-run = "main"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"

[dependencies]
tikv-jemallocator = "0.6.1"
clap = {version = "4.5.50", features = ["derive"]}
nom = "8.0.0"
roaring = "0.11.3"
rayon = "1.11.0"
cpu-time = "1.0.0"
walkdir = "2.5"
gnuplot = "0.0.46"
itertools = "0.14.0"
rand = "0.9.2"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
smallvec = "1.15.1"
priority-queue = "2.7.0"

[dev-dependencies]
datatest-stable = "0.3"
criterion = "0.5"

[[test]]
name = "required_tests"
harness = false

# [[test]]
# name = "all_provided_inputs"
# harness = false

[[bench]]
name = "bench"
harness = false
